name: Deploy via SSH

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy via SSH (rsync method)
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Create a temporary directory
          mkdir -p /tmp/deploy-temp
          
    - name: Copy files with rsync (better method)
      uses: burnett01/rsync-deployments@6.0.0
      with:
        switches: -avz --delete
        path: ./
        remote_path: /var/www/html/simple-webpage/
        remote_host: ${{ secrets.SSH_HOST }}
        remote_user: ${{ secrets.SSH_USERNAME }}
        remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
        exclude: |
          .git/
          .github/
          .gitignore
          README.md
          
    - name: Set permissions and restart Apache
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          sudo chown -R www-data:www-data /var/www/html/simple-webpage/
          sudo chmod -R 755 /var/www/html/simple-webpage/
          sudo systemctl restart apache2
